Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceStore.Data;
using EcommerceStore.Model;
using EcommerceStore.Serivce;
using EcommerceStore.Web.Areas.Admin.ViewModel;

namespace EcommerceStore.Web.Areas.Admin.Controllers
{
    public class CategoryController : Controller
    {
        private CategorySerivce categorySerivce = new CategorySerivce();
        private EcommerceStoreContext db = new EcommerceStoreContext();

        // GET: Admin/Category
        public ActionResult Index()
        {
            EcommerceStoreCategoryList ecommerceStoreCategoryList = new EcommerceStoreCategoryList();
           ecommerceStoreCategoryList.categories = categorySerivce.GetAllEcommerceStoreCategories();
            return View(ecommerceStoreCategoryList);
        }

        //public ActionResult Listing()
        //{

        //    return View();
        //}

        public ActionResult Action(int? Id)
        {
            var model = new EcommerceStoreViewCategory();

            if(Id.HasValue)
            {
                var categroy = categorySerivce.GetCategroyId(Id.Value);
                model.Id = categroy.Id;
                model.Name = categroy.Name;
                model.CategroyImage = categroy.CategoryImage;
            }

            return PartialView("_Action", model);
        }



        [HttpPost]
        public JsonResult Action([Bind(Include = "Id,Name,CategoryImage")] Category CategoryModel,HttpPostedFileBase CategoryImage)
        {
            JsonResult json = new JsonResult();
            
            bool result = false;

            if (CategoryModel.Id > 0)
            {
                var OldCategoryImage = Request.MapPath(db.Categories.Find(CategoryModel.Id).CategoryImage.ToString()); 
                
                Category category = new Category();

                string FilePath = Server.MapPath("~/Areas/Admin/Image/CategoryImage/");

                string FileName = Path.GetFileName(CategoryImage.FileName);
                string _FileName = DateTime.Now.ToString("yyyymmssfff") + FileName;
                string Exesption = Path.GetExtension(CategoryImage.FileName);
                string path = Path.Combine(FilePath, _FileName);

                category.Id = CategoryModel.Id;
                category.Name = CategoryModel.Name;
                category.CategoryImage = "~/Areas/Admin/Image/CategoryImage/" + _FileName;

                if(Exesption.ToLower() == ".png" || Exesption.ToLower() == ".jepg" || Exesption.ToLower() == ".jpg")
                {
                    if(CategoryImage.ContentLength < 10000000)
                    {
                        result = categorySerivce.EditEcommerceStoreCategory(category);
                        if (result)
                        {

                            CategoryImage.SaveAs(path);
                            if (System.IO.File.Exists(OldCategoryImage))
                            {
                                System.IO.File.Delete(OldCategoryImage);
                              
                            }
                        }
                    }
                }
            }
            else
            {
                Category category = new Category();
                if(CategoryImage != null)
                {
                    string FilePath = Server.MapPath("~/Areas/Admin/Image/CategoryImage/");
                    if (!Directory.Exists(FilePath))
                    {
                        Directory.CreateDirectory(FilePath);
                    }
                    string FileName = Path.GetFileName(CategoryImage.FileName);
                    string _FileName = DateTime.Now.ToString("yyyymmssfff") + FileName;
                    string exesption = Path.GetExtension(CategoryImage.FileName);
                    string path = Path.Combine(FilePath, _FileName);
                    category.Name = CategoryModel.Name;
                    category.CategoryImage = "~/Areas/Admin/Image/CategoryImage/" + _FileName;
                    if(exesption.ToLower() == ".jpg" || exesption.ToLower() == ".jepg" || exesption.ToLower() == ".png")
                    {
                        if(CategoryImage.ContentLength < 10000000)
                        {
                            result = categorySerivce.SaveEcommerceStoreCategory(category);
                            if (result)
                            {
                                CategoryImage.SaveAs(path);
                            }
                        }
                    }
                }
                else
                {
                    category.Name = CategoryModel.Name;
                    result = categorySerivce.SaveEcommerceStoreCategory(category);
                }
               
            }

          

            

            if (result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false ,Message = "上傳時出現問題!"};
            }


            return json;
        }

     
        // GET: Admin/Category/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", category);
        }

        // POST: Admin/Category/Delete/5
        [HttpPost]
        
        public JsonResult Delete(Category category)
        {

            JsonResult json = new JsonResult ();
            bool Result = false;
            var DeleteCategroy = categorySerivce.GetCategroyId(category.Id);
            Result = categorySerivce.DeleteEcommerceStoreCategroy(DeleteCategroy);

            if (Result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "刪除失敗!" };
            }
            return json;
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Controllers/ProudctController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceStore.Data;
using EcommerceStore.Model;

namespace EcommerceStore.Web.Areas.Admin.Controllers
{
    public class ProudctController : Controller
    {
        private EcommerceStoreContext db = new EcommerceStoreContext();

        // GET: Admin/Proudct
        public ActionResult Index()
        {
            var proudcts = db.Proudcts.Include(p => p.Category).Include(p => p.Discount);
            return View(proudcts.ToList());
        }

        // GET: Admin/Proudct/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proudct proudct = db.Proudcts.Find(id);
            if (proudct == null)
            {
                return HttpNotFound();
            }
            return View(proudct);
        }

        // GET: Admin/Proudct/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name");
            ViewBag.DiscountId = new SelectList(db.Discounts, "Id", "Name");
            return View();
        }

        // POST: Admin/Proudct/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Decsription,Stock_Keep,CategoryId,price,DiscountId,ProudctImage,Create_at,Modified_at")] Proudct proudct)
        {
            if (ModelState.IsValid)
            {
                db.Proudcts.Add(proudct);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", proudct.CategoryId);
            ViewBag.DiscountId = new SelectList(db.Discounts, "Id", "Name", proudct.DiscountId);
            return View(proudct);
        }

        // GET: Admin/Proudct/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proudct proudct = db.Proudcts.Find(id);
            if (proudct == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", proudct.CategoryId);
            ViewBag.DiscountId = new SelectList(db.Discounts, "Id", "Name", proudct.DiscountId);
            return View(proudct);
        }

        // POST: Admin/Proudct/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Decsription,Stock_Keep,CategoryId,price,DiscountId,ProudctImage,Create_at,Modified_at")] Proudct proudct)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proudct).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Categories, "Id", "Name", proudct.CategoryId);
            ViewBag.DiscountId = new SelectList(db.Discounts, "Id", "Name", proudct.DiscountId);
            return View(proudct);
        }

        // GET: Admin/Proudct/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proudct proudct = db.Proudcts.Find(id);
            if (proudct == null)
            {
                return HttpNotFound();
            }
            return View(proudct);
        }

        // POST: Admin/Proudct/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Proudct proudct = db.Proudcts.Find(id);
            db.Proudcts.Remove(proudct);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.88.1">
    <title>Dashboard Template · Bootstrap v5.1</title>
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <link rel="canonical" href="https://getbootstrap.com/docs/5.1/examples/dashboard/">
    <link href="~/Content/jquery-ui.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.structure.css" rel="stylesheet" />
    <link href="~/Content/jquery-ui.theme.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-ui.js"></script>
    <!-- Bootstrap core CSS -->

    <link href="~/CSS/dashboardcss/dashboard.css" rel="stylesheet" />
    <link href="~/CSS/css/bootstrap.min.css" rel="stylesheet" />

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @*@media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }*@
    </style>


    <!-- Custom styles for this template -->

</head>
<body>

    <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">商品後端中心</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
        <div class="navbar-nav">
            <div class="nav-item text-nowrap">
                <a class="nav-link px-3" href="#">登出</a>
            </div>
        </div>
    </header>

    <div class="container-fluid">
        <div class="row">
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="position-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" href="#">
                                <span data-feather="home"></span>
                                會員中心
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file"></span>
                                Orders
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Proudct")">
                                <span data-feather="shopping-cart"></span>
                                商品管理
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Category")">
                                <span data-feather="users"></span>
                                分類
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="@Url.Action("Index","Discounts")">
                                <span data-feather="bar-chart-2"></span>
                                折扣活動
                            </a>
                        </li>
                       
                    </ul>

                    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                        <span>Saved reports</span>
                        <a class="link-secondary" href="#" aria-label="Add a new report">
                            <span data-feather="plus-circle"></span>
                        </a>
                    </h6>
                    <ul class="nav flex-column mb-2">
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Current month
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Last quarter
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Social engagement
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">
                                <span data-feather="file-text"></span>
                                Year-end sale
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>
            
        <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
            @RenderBody()
            
        </main>
        </div>
    </div>


    <script src="~/Scripts/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="~/Scripts/dashboardjs/dashboard.js"></script>
</body>
</html>