Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Controllers/DiscountsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using EcommerceStore.Data;
using EcommerceStore.Model;
using EcommerceStore.Web.Areas.Admin.ViewModel;
using EcommerceStore.Serivce;
using System.IO;

namespace EcommerceStore.Web.Areas.Admin.Controllers
{
    public class DiscountsController : Controller
    {
        private EcommerceStoreContext db = new EcommerceStoreContext();
        private DiscountSerivce discountSerivce = new DiscountSerivce();

        // GET: Admin/Discount
        public ActionResult Index()
        {
            EcommerceStoreDiscountList ecommerceStoreDiscountList = new EcommerceStoreDiscountList();
            ecommerceStoreDiscountList.discounts = discountSerivce.GetAllEcommerceDiscounts();

            return View(ecommerceStoreDiscountList);
        }


        //public ActionResult Listing()
        //{
        //    return PartialView("_Listing");
        //}

        public ActionResult Action(int? Id)
        {
            EcommerceStoreDiscount ecommerceStoreDiscount = new EcommerceStoreDiscount();
            if (Id.HasValue)
            {
               
                var Discount = discountSerivce.GetEcommerceStoreDiscountID(Id.Value);
                ecommerceStoreDiscount.Id = Id.Value;
                ecommerceStoreDiscount.Name = Discount.Name;
                ecommerceStoreDiscount.StartDiscount = (DateTime)Discount.StartDiscount;
                ecommerceStoreDiscount.DescriptImage = Discount.DescriptImage;
                ecommerceStoreDiscount.Description = Discount.Description;
                ecommerceStoreDiscount.DiscountPreceint = Discount.DiscountPreceint;
                ecommerceStoreDiscount.enabled = Discount.enabled;
                ecommerceStoreDiscount.EndDiscount = (DateTime)Discount.EndDiscount;

            }
            return PartialView("_Action", ecommerceStoreDiscount);
        }

        [HttpPost]
        public JsonResult Action([Bind(Include = "Id,Name,Description,DescriptImage,DiscountPreceint,enabled,StartDiscount,EndDiscount,Create_at")] Discount discount, HttpPostedFileBase DiscountImage)
        {
            JsonResult json = new JsonResult();
            var Result = false;


            //更新折扣
            if (discount.Id > 0)
            {
                Discount teamdiscount = discountSerivce.GetEcommerceStoreDiscountID(discount.Id);
                string OldDiscountImage = Request.MapPath(db.Discounts.Find(discount.Id).DescriptImage.ToString());
                string FilePath = Server.MapPath("~/Areas/Admin/Image/Discount/");
                string FileName = Path.GetFileName(DiscountImage.FileName);
                string _FileName = DateTime.Now.ToString("yyyymmssfff") + FileName;
                string exesption = Path.GetExtension(DiscountImage.FileName);
                string path = Path.Combine(FilePath, _FileName);

                Discount Editdiscount = new Discount
                {
                    Id = discount.Id,
                    Name = discount.Name,
                    Description = discount.Description,
                    DescriptImage = "~/Areas/Admin/Image/Discount/" + _FileName,
                    DiscountPreceint = discount.DiscountPreceint,
                    enabled = discount.enabled,
                    StartDiscount = discount.StartDiscount,
                    EndDiscount = discount.EndDiscount,
                    Create_at = teamdiscount.Create_at,
                    Modified_at = DateTime.Now,

                };


                if (exesption.ToLower() == ".png" || exesption.ToLower() == ".peng" || exesption.ToLower() == ".jpg")
                {
                    if (DiscountImage.ContentLength < 10000000000)
                    {
                        Result = discountSerivce.EditEcommerceStoreDiscounts(Editdiscount);
                        if (Result)
                        {
                            DiscountImage.SaveAs(path);
                            if (System.IO.File.Exists(OldDiscountImage))
                            {
                                System.IO.File.Delete(OldDiscountImage);
                            }
                        }
                    }
                }
            }
            else
            {

                //新增折扣
                string FilePath = Server.MapPath("~/Areas/Admin/Image/Discount/");
                if (!Directory.Exists(FilePath))
                {
                    Directory.CreateDirectory(FilePath);
                }
                string FileName = Path.GetFileName(DiscountImage.FileName);
                string _FileName = DateTime.Now.ToString("yyyymmssfff") + FileName;
                string exesption = Path.GetExtension(DiscountImage.FileName);
                string path = Path.Combine(FilePath, _FileName);


                discount.Create_at = DateTime.Now;
                discount.Modified_at = DateTime.Now;
                discount.DescriptImage = "~/Areas/Admin/Image/Discount/" + _FileName;


                if (exesption.ToLower() == ".png" || exesption.ToLower() == ".peng" || exesption.ToLower() == ".jpg")
                {
                    if (DiscountImage.ContentLength < 10000000000)
                    {
                        Result = discountSerivce.SaveEcommerceStoreDiscounts(discount);
                        if (Result)
                        {
                            DiscountImage.SaveAs(path);
                        }
                    }
                }

            }


            if (Result)
            {
                json.Data = new { Success = true };

            }
            else
            {
                json.Data = new { Success = false, Message = "新增尚未成功!" };
            }


            return json;
        }



        // GET: Admin/Discount/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Discount discount = db.Discounts.Find(id);
            if (discount == null)
            {
                return HttpNotFound();
            }
            return PartialView("_Delete", discount);
        }

        // POST: Admin/Discount/Delete/5
        [HttpPost]
        public JsonResult Delete(Discount discount)
        {
            JsonResult json = new JsonResult();
            bool Result = false;
            var DeleteDiscount = discountSerivce.GetEcommerceStoreDiscountID(discount.Id);

            Result = discountSerivce.DeleteEcommerceStoreDiscounts(DeleteDiscount);

            if (Result)
            {
                json.Data = new { Success = true };
            }
            else
            {
                json.Data = new { Success = false, Message = "刪除失敗!" };
            }

            return json;
        }






        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Views/Discounts/Index.cshtml
@model EcommerceStore.Web.Areas.Admin.ViewModel.EcommerceStoreDiscountList


<h1 class="mt-4">活動折扣</h1>
<ol class="breadcrumb p-3 pb-md-4 mx-auto text-center">
    <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
    <li class="breadcrumb-item active">Sidenav Light</li>
</ol>



<!-- Button trigger modal -->
<button id="ActionButton" data-href="@Url.Action("Action","Discounts")" type="button" class="data-btn btn btn-primary" data-bs-toggle="modal" data-bs-target="#ActionModal">
    新增
</button>


<div class="table-responsive">

    @{
        Html.RenderPartial("_Listing", Model);
    }

</div>



<!-- Modal -->
<div class="modal fade" id="ActionModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">

    </div>
</div>


<script>
    $(".data-btn").click(function () {
        $.ajax({
            url: $(this).attr("data-href")

        }).done(function (response) {
            $("#ActionModal .modal-dialog").html(response);
        });
    });
</script>

Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Views/Discounts/_Action.cshtml
@model EcommerceStore.Web.Areas.Admin.ViewModel.EcommerceStoreDiscount


@if (Model != null)
{
    <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">折扣活動</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form id="ActionForm">
                <input type="hidden" name="Id" value="@Model.Id">
                <div class="mb-3">
                    <h4 for="exampleInputEmail1" class="form-label">活動名稱</h4>
                    <input type="text" class="form-control" id="DiscountName" name="Name" value="@Model.Name">
                </div>

                <div class="mb-3">
                    <h4 for="exampleInputEmail1" class="form-label">折扣</h4>
                    <input type="number" step=0.01 class="form-control" id="Discountpreceint" name="DiscountPreceint" value="@Model.DiscountPreceint">
                </div>

                <div class="mb-3">

                    <div class="row g-2">

                        <div class="col">
                            <label class="form-label">開始日期</label>
                            
                            <input type="text" id="StartDiscountTime" class="form-control" value="@Model.StartDiscount.ToString("yyyy-MMM-dd")">
                        </div>
                        <div class="col">
                            <label class="form-label">結束日期</label>
                            <input type="text" id="EndDiscountTime" class="form-control" value="@Model.EndDiscount.ToString("yyyy-MMM-dd")">
                        </div>
                    </div>
                </div>


                <div class="mb-3">
                    <h4 class="form-label">活動內容</h4>
                    <div class="form-floating">
                        <textarea class="form-control" id="DescriptionDiscount" name="Description" placeholder="Leave a comment here" id="floatingTextarea2" style="height: 100px">@Model.Description</textarea>
                        <label for="floatingTextarea2">內容</label>
                    </div>
                </div>

                <div class="mb-3">
                    <h4 for="formFile" class="form-label">活動圖片</h4>
                    <input id="DiscountImageView" class="form-control" name="DiscountImage" type="file" id="formFile">
                    <div class="text-center">
                        <img id="DiscountImageView" src="" class="rounded" width="200">
                    </div>

                </div>


                <div class="form-check form-switch">
                    <input class="form-check-input" type="checkbox" role="switch" name="enabled" id="DiscountEnabledTrue" value="@Model.enabled">
                    <label class="form-check-label" for="flexSwitchCheckDefault">是否公開</label>
                </div>

            </form>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
            <button id="SaveButton" type="button" class="btn btn-primary">儲存</button>
        </div>
        <div class="alert alert-danger" role="alert" id="ErrorDiscount">

        </div>
    </div>

}

    <script>
    $("#DiscountImage").change(function () {
        readURL(this);
    });
    function readURL(input) {
        if (input.files && input.files[0]) {
            var vendor = new FileReader();
            vendor.onload = function (e) {
                $("#DiscountImageView").attr("src", e.target.result);
            }
            vendor.readAsDataURL(input.files[0]);
        }
    }


        $(document).ready(function () {
            $('#StartDiscountTime').datepicker({
                dateFormat: "yy/MM/dd",
                changeMonth: true,
                changeYear: true
            });
        });

        $(document).ready(function () {
            $('#EndDiscountTime').datepicker({
                dateFormat: "yy/MM/dd",
                changeMonth: true,
                changeYear: true
            });
        });
    $("#SaveButton").click(function () {



        var DiscountFormData = new FormData;
        var Name = $("#DiscountName").val();
        var Description = $("#DescriptionDiscount").val();
        var DiscountImage = $("#DiscountImageView")[0].files[0];
        var Preceint = $("#Discountpreceint").val();
        var DiscountEnabled = $("#DiscountEnabledTrue").val();
        var StartDisocunt = $("#StartDiscountTime").val();
        var EndDiscount = $("#EndDiscountTime").val();


        DiscountFormData.append("Name", Name);
        DiscountFormData.append("Description", Description);
        DiscountFormData.append("DiscountImage", DiscountImage);
        DiscountFormData.append("DiscountPreceint", Preceint);
        DiscountFormData.append("enabled", DiscountEnabled);
        DiscountFormData.append("StartDiscount", StartDisocunt);
        DiscountFormData.append("EndDiscount", EndDiscount);

        $.ajax({
            url: "@Url.Action("Action","Discounts")",
            type: "POST",
            processData: false,
            contentType: false,
            data: DiscountFormData,
        }).done(function (response) {
            debugger;
            if (response.Success) {
                location.reload();
            } else {
                $("#ErrorDiscount").html(response.Message);
            }
        });

    });






    </script>

Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Views/Discounts/_Delete.cshtml
@model EcommerceStore.Model.Discount

<div class="modal-content">
    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">刪除 @Model.Name 活動</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>
    <div class="modal-body">
        <form id="ActionForm">
            <input type="hidden" name="Id" value="@Model.Id">
        </form>
        <div class="alert alert-danger" role="alert">
            你確定要刪除嗎?
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">關閉</button>
        <button id="DeleteButton" type="button" class="btn btn-primary">刪除</button>
    </div>

</div>

<div class="alert alert-danger" role="alert" id="ErrorDiscount">

</div>
<script>
    $("#DeleteButton").click(function () {
        $.ajax({
            url: "@Url.Action("Delete", "Discounts")",
            type: "post",
            data: $("#ActionForm").serialize(),
        }).done(function (respsone) {
            debugger;
            if (respsone.Success) {
                window.location.href = "@Url.Action("Index", "Discounts")";
            } else {
                $("#ErrorDiscount").html(respsone.Message)
            }
        });
    });
</script>









Ecommerce_Store/EcommerceStore/EcommerceStore.Web/Areas/Admin/Views/Discounts/_Listing.cshtml
@model EcommerceStore.Web.Areas.Admin.ViewModel.EcommerceStoreDiscountList
@{
    ViewBag.Title = "_Listing";
}

@if (Model != null && Model.discounts.Count() > 0)
{
    <table class="table table-striped">
        <thead>
            <tr>
                <th></th>
                <th>名字</th>
                <th>折扣</th>
                <th>活動內容</th>
                <th>開始日期</th>
                <th>結束日期</th>
                <th>圖片</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var Discount in Model.discounts)
            {
            <tr>

                <td>@Discount.Id</td>

                <td>@Discount.Name</td>
                <td>@Discount.DiscountPreceint</td>
                <td>@Discount.Description</td>
                <td>

                    @Discount.StartDiscount.ToString("yyyy-MM-dd")
                </td>
                <td>

                    @Discount.EndDiscount.ToString("yyyy-MM-dd")
                </td>
                <td>
                    <img src="@Url.Content(Discount.DescriptImage)" title="@Discount.Name" />
                </td>
                <td>

                    <button id="ActionButton" data-href="@Url.Action("Action", "Discounts", new { Id = Discount.Id })" type="button" class="data-btn btn btn-success" data-bs-toggle="modal" data-bs-target="#ActionModal">更新</button>

                    <!--<-->@*button type="button" data-href="@Url.Action("Delete", "Discount", new { Id = Discount.Id })" class="data-btn btn btn-success" data-bs-toggle="modal" data-bs-target="#ActionModal"><i class="fas fa-trash-alt mr-1"></i>刪除</button>*@


                    <button id="ActionButton" data-href="@Url.Action("Delete", "Discounts", new { Id = Discount.Id })" type="button" class="data-btn btn btn-success" data-bs-toggle="modal" data-bs-target="#ActionModal">刪除</button>
                </td>


            </tr>
            }



        </tbody>
    </table>
}
else
{
    <div class="alert alert-warning" role="alert">
       <h3>抱歉!!  現在還沒有資料!!</h3>
    </div>

}

